import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import { Barlow, IBM_Plex_Mono } from "next/font/google";
import ServiceTab from "./components/ServiceTab";

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-barlow",
});

const mono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title:
    "Softwareproduktiv GmbH – Software for the skilled trades that works in everyday life",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="de"
      className={`${barlow.variable} ${mono.variable} h-full antialiased`}
    >
      <body>
        <Header />
        <ServiceTab />
        {children}
        <Footer />
      </body>
    </html>
  );
}
